// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.1
// source: rpc_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Login                   string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password                string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Realm                   string                 `protobuf:"bytes,3,opt,name=realm,proto3" json:"realm,omitempty"`
	AccessExpiresInSeconds  *int64                 `protobuf:"varint,4,opt,name=access_expires_in_seconds,json=accessExpiresInSeconds,proto3,oneof" json:"access_expires_in_seconds,omitempty"`
	RefreshExpiresInSeconds *int64                 `protobuf:"varint,5,opt,name=refresh_expires_in_seconds,json=refreshExpiresInSeconds,proto3,oneof" json:"refresh_expires_in_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_rpc_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *UserRequest) GetAccessExpiresInSeconds() int64 {
	if x != nil && x.AccessExpiresInSeconds != nil {
		return *x.AccessExpiresInSeconds
	}
	return 0
}

func (x *UserRequest) GetRefreshExpiresInSeconds() int64 {
	if x != nil && x.RefreshExpiresInSeconds != nil {
		return *x.RefreshExpiresInSeconds
	}
	return 0
}

type AuthIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthIdRequest) Reset() {
	*x = AuthIdRequest{}
	mi := &file_rpc_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthIdRequest) ProtoMessage() {}

func (x *AuthIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthIdRequest.ProtoReflect.Descriptor instead.
func (*AuthIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AuthIdRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthIdRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_rpc_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LogoutRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

type StatusIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusIn) Reset() {
	*x = StatusIn{}
	mi := &file_rpc_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusIn) ProtoMessage() {}

func (x *StatusIn) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusIn.ProtoReflect.Descriptor instead.
func (*StatusIn) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{3}
}

func (x *StatusIn) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StatusIn) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type StatusOut struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenValid  bool                   `protobuf:"varint,1,opt,name=accessTokenValid,proto3" json:"accessTokenValid,omitempty"`
	RefreshTokenValid bool                   `protobuf:"varint,2,opt,name=refreshTokenValid,proto3" json:"refreshTokenValid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusOut) Reset() {
	*x = StatusOut{}
	mi := &file_rpc_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusOut) ProtoMessage() {}

func (x *StatusOut) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusOut.ProtoReflect.Descriptor instead.
func (*StatusOut) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{4}
}

func (x *StatusOut) GetAccessTokenValid() bool {
	if x != nil {
		return x.AccessTokenValid
	}
	return false
}

func (x *StatusOut) GetRefreshTokenValid() bool {
	if x != nil {
		return x.RefreshTokenValid
	}
	return false
}

type RefreshIn struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken            string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessExpiresInSeconds  *int64                 `protobuf:"varint,2,opt,name=access_expires_in_seconds,json=accessExpiresInSeconds,proto3,oneof" json:"access_expires_in_seconds,omitempty"`
	RefreshExpiresInSeconds *int64                 `protobuf:"varint,3,opt,name=refresh_expires_in_seconds,json=refreshExpiresInSeconds,proto3,oneof" json:"refresh_expires_in_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RefreshIn) Reset() {
	*x = RefreshIn{}
	mi := &file_rpc_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshIn) ProtoMessage() {}

func (x *RefreshIn) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshIn.ProtoReflect.Descriptor instead.
func (*RefreshIn) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshIn) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshIn) GetAccessExpiresInSeconds() int64 {
	if x != nil && x.AccessExpiresInSeconds != nil {
		return *x.AccessExpiresInSeconds
	}
	return 0
}

func (x *RefreshIn) GetRefreshExpiresInSeconds() int64 {
	if x != nil && x.RefreshExpiresInSeconds != nil {
		return *x.RefreshExpiresInSeconds
	}
	return 0
}

type RefreshOut struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpiresAt  int64                  `protobuf:"varint,2,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshExpiresAt int64                  `protobuf:"varint,4,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefreshOut) Reset() {
	*x = RefreshOut{}
	mi := &file_rpc_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshOut) ProtoMessage() {}

func (x *RefreshOut) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshOut.ProtoReflect.Descriptor instead.
func (*RefreshOut) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshOut) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshOut) GetAccessExpiresAt() int64 {
	if x != nil {
		return x.AccessExpiresAt
	}
	return 0
}

func (x *RefreshOut) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshOut) GetRefreshExpiresAt() int64 {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return 0
}

type EditUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewLogin      string                 `protobuf:"bytes,1,opt,name=new_login,json=newLogin,proto3" json:"new_login,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserRequest) Reset() {
	*x = EditUserRequest{}
	mi := &file_rpc_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserRequest) ProtoMessage() {}

func (x *EditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserRequest.ProtoReflect.Descriptor instead.
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{7}
}

func (x *EditUserRequest) GetNewLogin() string {
	if x != nil {
		return x.NewLogin
	}
	return ""
}

func (x *EditUserRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *EditUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActionRequest) Reset() {
	*x = UserActionRequest{}
	mi := &file_rpc_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActionRequest) ProtoMessage() {}

func (x *UserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActionRequest.ProtoReflect.Descriptor instead.
func (*UserActionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{8}
}

func (x *UserActionRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserActionRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *UserActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UserActionRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UserActionValidation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Login             string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Realm             string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Data              string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Against           string                 `protobuf:"bytes,4,opt,name=against,proto3" json:"against,omitempty"`
	SelfContainedCode bool                   `protobuf:"varint,5,opt,name=self_contained_code,json=selfContainedCode,proto3" json:"self_contained_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserActionValidation) Reset() {
	*x = UserActionValidation{}
	mi := &file_rpc_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActionValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActionValidation) ProtoMessage() {}

func (x *UserActionValidation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActionValidation.ProtoReflect.Descriptor instead.
func (*UserActionValidation) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{9}
}

func (x *UserActionValidation) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserActionValidation) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *UserActionValidation) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UserActionValidation) GetAgainst() string {
	if x != nil {
		return x.Against
	}
	return ""
}

func (x *UserActionValidation) GetSelfContainedCode() bool {
	if x != nil {
		return x.SelfContainedCode
	}
	return false
}

type UserActionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ValidatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActionStatus) Reset() {
	*x = UserActionStatus{}
	mi := &file_rpc_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActionStatus) ProtoMessage() {}

func (x *UserActionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActionStatus.ProtoReflect.Descriptor instead.
func (*UserActionStatus) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{10}
}

func (x *UserActionStatus) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserActionStatus) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *UserActionStatus) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UserActionStatus) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UserActionStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserActionStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserActionStatus) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

type UserActionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Statuses      []*UserActionStatus    `protobuf:"bytes,3,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActionStatusResponse) Reset() {
	*x = UserActionStatusResponse{}
	mi := &file_rpc_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActionStatusResponse) ProtoMessage() {}

func (x *UserActionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActionStatusResponse.ProtoReflect.Descriptor instead.
func (*UserActionStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{11}
}

func (x *UserActionStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserActionStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserActionStatusResponse) GetStatuses() []*UserActionStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Identifier    string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_rpc_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rpc_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{13}
}

type UserFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=login,proto3,oneof" json:"login,omitempty"`
	Realm         *string                `protobuf:"bytes,2,opt,name=realm,proto3,oneof" json:"realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilters) Reset() {
	*x = UserFilters{}
	mi := &file_rpc_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilters) ProtoMessage() {}

func (x *UserFilters) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilters.ProtoReflect.Descriptor instead.
func (*UserFilters) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{14}
}

func (x *UserFilters) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *UserFilters) GetRealm() string {
	if x != nil && x.Realm != nil {
		return *x.Realm
	}
	return ""
}

type UsersInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersInfo) Reset() {
	*x = UsersInfo{}
	mi := &file_rpc_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersInfo) ProtoMessage() {}

func (x *UsersInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersInfo.ProtoReflect.Descriptor instead.
func (*UsersInfo) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{15}
}

func (x *UsersInfo) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Realm         string                 `protobuf:"bytes,2,opt,name=realm,proto3" json:"realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_rpc_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_rpc_v1_proto_rawDescGZIP(), []int{16}
}

func (x *UserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfo) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

var File_rpc_v1_proto protoreflect.FileDescriptor

const file_rpc_v1_proto_rawDesc = "" +
	"\n" +
	"\frpc_v1.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\vUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05realm\x18\x03 \x01(\tR\x05realm\x12>\n" +
	"\x19access_expires_in_seconds\x18\x04 \x01(\x03H\x00R\x16accessExpiresInSeconds\x88\x01\x01\x12@\n" +
	"\x1arefresh_expires_in_seconds\x18\x05 \x01(\x03H\x01R\x17refreshExpiresInSeconds\x88\x01\x01B\x1c\n" +
	"\x1a_access_expires_in_secondsB\x1d\n" +
	"\x1b_refresh_expires_in_seconds\"9\n" +
	"\rAuthIdRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x05R\x03uid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\rLogoutRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x05R\x03uid\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\"P\n" +
	"\bStatusIn\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"e\n" +
	"\tStatusOut\x12*\n" +
	"\x10accessTokenValid\x18\x01 \x01(\bR\x10accessTokenValid\x12,\n" +
	"\x11refreshTokenValid\x18\x02 \x01(\bR\x11refreshTokenValid\"\xee\x01\n" +
	"\tRefreshIn\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\x12>\n" +
	"\x19access_expires_in_seconds\x18\x02 \x01(\x03H\x00R\x16accessExpiresInSeconds\x88\x01\x01\x12@\n" +
	"\x1arefresh_expires_in_seconds\x18\x03 \x01(\x03H\x01R\x17refreshExpiresInSeconds\x88\x01\x01B\x1c\n" +
	"\x1a_access_expires_in_secondsB\x1d\n" +
	"\x1b_refresh_expires_in_seconds\"\xac\x01\n" +
	"\n" +
	"RefreshOut\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12*\n" +
	"\x11access_expires_at\x18\x02 \x01(\x03R\x0faccessExpiresAt\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\x12,\n" +
	"\x12refresh_expires_at\x18\x04 \x01(\x03R\x10refreshExpiresAt\"m\n" +
	"\x0fEditUserRequest\x12\x1b\n" +
	"\tnew_login\x18\x01 \x01(\tR\bnewLogin\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"k\n" +
	"\x11UserActionRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"\xa0\x01\n" +
	"\x14UserActionValidation\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x18\n" +
	"\aagainst\x18\x04 \x01(\tR\aagainst\x12.\n" +
	"\x13self_contained_code\x18\x05 \x01(\bR\x11selfContainedCode\"\x9f\x02\n" +
	"\x10UserActionStatus\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fvalidated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vvalidatedAt\"z\n" +
	"\x18UserActionStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bstatuses\x18\x03 \x03(\v2\x14.v1.UserActionStatusR\bstatuses\"X\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\"\a\n" +
	"\x05Empty\"W\n" +
	"\vUserFilters\x12\x19\n" +
	"\x05login\x18\x01 \x01(\tH\x00R\x05login\x88\x01\x01\x12\x19\n" +
	"\x05realm\x18\x02 \x01(\tH\x01R\x05realm\x88\x01\x01B\b\n" +
	"\x06_loginB\b\n" +
	"\x06_realm\"/\n" +
	"\tUsersInfo\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.v1.UserInfoR\x05users\"6\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05realm\x18\x02 \x01(\tR\x05realm2\xb5\x01\n" +
	"\x04Auth\x12)\n" +
	"\x06Signup\x12\x0f.v1.UserRequest\x1a\f.v1.Response\"\x00\x12(\n" +
	"\x05Login\x12\x0f.v1.UserRequest\x1a\f.v1.Response\"\x00\x12+\n" +
	"\x06Delete\x12\x11.v1.AuthIdRequest\x1a\f.v1.Response\"\x00\x12+\n" +
	"\x06Logout\x12\x11.v1.LogoutRequest\x1a\f.v1.Response\"\x002Z\n" +
	"\x03JWT\x12'\n" +
	"\x06Status\x12\f.v1.StatusIn\x1a\r.v1.StatusOut\"\x00\x12*\n" +
	"\aRefresh\x12\r.v1.RefreshIn\x1a\x0e.v1.RefreshOut\"\x002`\n" +
	"\x04User\x12'\n" +
	"\n" +
	"Deactivate\x12\t.v1.Empty\x1a\f.v1.Response\"\x00\x12/\n" +
	"\bEditUser\x12\x13.v1.EditUserRequest\x1a\f.v1.Response\"\x002\xb4\x01\n" +
	"\n" +
	"UserAction\x12/\n" +
	"\x06Create\x12\x15.v1.UserActionRequest\x1a\f.v1.Response\"\x00\x124\n" +
	"\bValidate\x12\x18.v1.UserActionValidation\x1a\f.v1.Response\"\x00\x12?\n" +
	"\x06Status\x12\x15.v1.UserActionRequest\x1a\x1c.v1.UserActionStatusResponse\"\x0024\n" +
	"\x04Info\x12,\n" +
	"\bGetUsers\x12\x0f.v1.UserFilters\x1a\r.v1.UsersInfo\"\x00B\rZ\vpkg/grpc/v1b\x06proto3"

var (
	file_rpc_v1_proto_rawDescOnce sync.Once
	file_rpc_v1_proto_rawDescData []byte
)

func file_rpc_v1_proto_rawDescGZIP() []byte {
	file_rpc_v1_proto_rawDescOnce.Do(func() {
		file_rpc_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_v1_proto_rawDesc), len(file_rpc_v1_proto_rawDesc)))
	})
	return file_rpc_v1_proto_rawDescData
}

var file_rpc_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_rpc_v1_proto_goTypes = []any{
	(*UserRequest)(nil),              // 0: v1.UserRequest
	(*AuthIdRequest)(nil),            // 1: v1.AuthIdRequest
	(*LogoutRequest)(nil),            // 2: v1.LogoutRequest
	(*StatusIn)(nil),                 // 3: v1.StatusIn
	(*StatusOut)(nil),                // 4: v1.StatusOut
	(*RefreshIn)(nil),                // 5: v1.RefreshIn
	(*RefreshOut)(nil),               // 6: v1.RefreshOut
	(*EditUserRequest)(nil),          // 7: v1.EditUserRequest
	(*UserActionRequest)(nil),        // 8: v1.UserActionRequest
	(*UserActionValidation)(nil),     // 9: v1.UserActionValidation
	(*UserActionStatus)(nil),         // 10: v1.UserActionStatus
	(*UserActionStatusResponse)(nil), // 11: v1.UserActionStatusResponse
	(*Response)(nil),                 // 12: v1.Response
	(*Empty)(nil),                    // 13: v1.Empty
	(*UserFilters)(nil),              // 14: v1.UserFilters
	(*UsersInfo)(nil),                // 15: v1.UsersInfo
	(*UserInfo)(nil),                 // 16: v1.UserInfo
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_rpc_v1_proto_depIdxs = []int32{
	17, // 0: v1.UserActionStatus.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: v1.UserActionStatus.updated_at:type_name -> google.protobuf.Timestamp
	17, // 2: v1.UserActionStatus.validated_at:type_name -> google.protobuf.Timestamp
	10, // 3: v1.UserActionStatusResponse.statuses:type_name -> v1.UserActionStatus
	16, // 4: v1.UsersInfo.users:type_name -> v1.UserInfo
	0,  // 5: v1.Auth.Signup:input_type -> v1.UserRequest
	0,  // 6: v1.Auth.Login:input_type -> v1.UserRequest
	1,  // 7: v1.Auth.Delete:input_type -> v1.AuthIdRequest
	2,  // 8: v1.Auth.Logout:input_type -> v1.LogoutRequest
	3,  // 9: v1.JWT.Status:input_type -> v1.StatusIn
	5,  // 10: v1.JWT.Refresh:input_type -> v1.RefreshIn
	13, // 11: v1.User.Deactivate:input_type -> v1.Empty
	7,  // 12: v1.User.EditUser:input_type -> v1.EditUserRequest
	8,  // 13: v1.UserAction.Create:input_type -> v1.UserActionRequest
	9,  // 14: v1.UserAction.Validate:input_type -> v1.UserActionValidation
	8,  // 15: v1.UserAction.Status:input_type -> v1.UserActionRequest
	14, // 16: v1.Info.GetUsers:input_type -> v1.UserFilters
	12, // 17: v1.Auth.Signup:output_type -> v1.Response
	12, // 18: v1.Auth.Login:output_type -> v1.Response
	12, // 19: v1.Auth.Delete:output_type -> v1.Response
	12, // 20: v1.Auth.Logout:output_type -> v1.Response
	4,  // 21: v1.JWT.Status:output_type -> v1.StatusOut
	6,  // 22: v1.JWT.Refresh:output_type -> v1.RefreshOut
	12, // 23: v1.User.Deactivate:output_type -> v1.Response
	12, // 24: v1.User.EditUser:output_type -> v1.Response
	12, // 25: v1.UserAction.Create:output_type -> v1.Response
	12, // 26: v1.UserAction.Validate:output_type -> v1.Response
	11, // 27: v1.UserAction.Status:output_type -> v1.UserActionStatusResponse
	15, // 28: v1.Info.GetUsers:output_type -> v1.UsersInfo
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_v1_proto_init() }
func file_rpc_v1_proto_init() {
	if File_rpc_v1_proto != nil {
		return
	}
	file_rpc_v1_proto_msgTypes[0].OneofWrappers = []any{}
	file_rpc_v1_proto_msgTypes[5].OneofWrappers = []any{}
	file_rpc_v1_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_v1_proto_rawDesc), len(file_rpc_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_rpc_v1_proto_goTypes,
		DependencyIndexes: file_rpc_v1_proto_depIdxs,
		MessageInfos:      file_rpc_v1_proto_msgTypes,
	}.Build()
	File_rpc_v1_proto = out.File
	file_rpc_v1_proto_goTypes = nil
	file_rpc_v1_proto_depIdxs = nil
}
